
// PLAYERS
POST http://localhost:5001/api/players/create
Content-Type: application/json

{
    "id": "123",
    "name": "neymar",
    "age": "31",
    "contry": "brazil",
    "team": "al hilal"
}

###
POST http://localhost:5001/api/players/create
Content-Type: application/json

{
    "id": "124",
    "name": "messi",
    "age": "36",
    "contry": "argentina",
    "team": "inter miami"
}

// PRODUCTS
###
POST http://localhost:5001/api/products/create
Content-Type: application/json

{
  "nome": "Batman",
  "id": "123456",
  "quantidade": 10,
  "preco": 29.99,
  "local": "Recife"
}


###
POST http://localhost:5001/api/products/create
Content-Type: application/json

{
  "nome": "Afagadores de bolas",
  "id": "123457",
  "quantidade": 20,
  "preco": 9.99,
  "local": "São Paulo"
}

###
GET http://localhost:5001/api/products/123456

###
POST http://localhost:5001/api/cart/create
Content-Type: application/json

{
    "nome": "Junior Silva",
    "cpf": "123.456.789-01",
    "dataNascimento": "25/10/2000",
    "email": "junior@example.com",
    "login": "juniorsilva",
    "senha": "senha_segura123",
    "logado": false
}

###
POST http://localhost:5001/api/users/cadastro
Content-Type: application/json

{
    "nome": "Maria Santos",
    "cpf": "123.456.789-02",
    "dataNascimento": "12/05/1995",
    "email": "maria@example.com",
    "login": "mariasantos",
    "senha": "senha123",
    "logado": false
}

###
POST http://localhost:5001/api/users/cadastro
Content-Type: application/json

{
    "nome": "João Oliveira",
    "cpf": "987.654.321-03",
    "dataNascimento": "08/09/1987",
    "email": "joao@example.com",
    "login": "joaooliveira",
    "senha": "segredodojoao",
    "logado": false
}


###
POST http://localhost:5001/api/users/cadastro
Content-Type: application/json

{
    "nome": "Ana Souza",
    "cpf": "456.789.012-04",
    "dataNascimento": "23/07/1990",
    "email": "ana@example.com",
    "login": "anasouza",
    "senha": "senhasupersegura",
    "logado": false
}


###
POST http://localhost:5001/api/users/cadastro
Content-Type: application/json

{
    "nome": "Pedro Lima",
    "cpf": "321.654.987-05",
    "dataNascimento": "18/03/1983",
    "email": "pedro@example.com",
    "login": "pedrolima",
    "senha": "senhapedro123",
    "logado": false
}


###
POST http://localhost:5001/api/users/cadastro
Content-Type: application/json

{
    "nome": "Carla Silva",
    "cpf": "789.012.345-06",
    "dataNascimento": "30/11/1978",
    "email": "carla@example.com",
    "login": "carlasilva",
    "senha": "senhacarla567",
    "logado": false
}

###
POST http://localhost:5001/api/users/cadastro
Content-Type: application/json

{
    "nome": "Airton Garcia",
    "cpf": "789.012.345-07",
    "dataNascimento": "30/11/1978",
    "email": "airton@example.com",
    "login": "airtongarcia",
    "senha": "senhaairton567",
    "logado": false
}
