
// PLAYERS
POST http://localhost:5001/api/players/create
Content-Type: application/json

{
    "id": "123",
    "name": "neymar",
    "age": "31",
    "contry": "brazil",
    "team": "al hilal"
}

###
POST http://localhost:5001/api/players/create
Content-Type: application/json

{
    "id": "124",
    "name": "messi",
    "age": "36",
    "contry": "argentina",
    "team": "inter miami"
}

// PRODUCTS
###
POST http://localhost:5001/api/products/create
Content-Type: application/json

{
  "nome": "Batman",
  "id": "123456",
  "quantidade": 10,
  "preco": 29.99,
  "local": "Recife"
}


###
POST http://localhost:5001/api/products/create
Content-Type: application/json

{
  "nome": "Afagadores de bolas",
  "id": "123457",
  "quantidade": 20,
  "preco": 9.99,
  "local": "São Paulo"
}

###
GET http://localhost:5001/api/products/123456

###
POST http://localhost:5001/api/cart/create
Content-Type: application/json

{
  "id":"123",
  "id_produtos":[],
  "quantidade":0,
  "data_criacao":"2024-03-03T20:38:17.880Z",
  "data_atualizacao":"2024-03-03T20:38:17.880Z"
}

###
GET http://localhost:5001/api/cart/123
###
