
POST http://localhost:5001/api/users/cadastro
Content-Type: application/json

{
    "nome": "Airton Garcia",
    "cpf": "13222020342",
    "dataNascimento": "30/11/1978",
    "email": "airton@example.com",
    "login": "airtongarcia2",
    "senha": "senhaairton567"
}

###

POST http://localhost:5001/api/emails/enviarEmail
Content-Type: application/json

{
    "remetente": "Júnior",
    "destinatario": "Rafael",
    "assunto": "É os guri!",
    "corpoEmail": "Bah tchê, é os guri!",
    "comprovante": "aloha",
    "isSpam": "false",
    "isDelivered": "false"
}

###
POST http://localhost:5001/api/login
Content-Type: application/json

{
    "login": "olak",
    "senha": "senha123"
}

### 
POST http://localhost:5001/api/login/logout/2
Content-Type: application/json

{
}