GET http://localhost:3001/restaurants

###

POST http://localhost:3001/restaurants
Content-Type: application/json

{
    "name": "Restaurante Genérico"
}

###

POST http://localhost:3001/restaurants
Content-Type: application/json

{
    "name": "Sei lá sushi"
}

###

DELETE http://localhost:3001/restaurant/delete/65c1a1e69308b1c17256d1a5

###

PUT http://localhost:3001/restaurant/edit/65c18a5cd486854c84a26574
Content-Type: application/json

{
    "name": "Restaurante Genérico 2"
}
